### ISSUE TITLE
Error message "All metabo_paths seem to be incorrect" in MS_keggNetwork function

### ISSUE THREAD

**Issue by Yun1229** [AndreaRMICL/MetaboSignal#4]
Hello Andrea,

Sorry to bother you again.
I am currently still using the MS_keggNetwork function in R, but I am encountering an error message that says "`All metabo_paths seem to be incorrect`", which is not shown before. This error message persists even when I run the example code:
`Error in MS_keggNetwork(metabo_paths = c("rno00010", "rno00562"), signaling_paths = c("rno04910",  : All metabo_paths seem to be incorrect`

I have checked that my BiocManager version is 3.17 and my R version is 4.3. 
I have also tried downgrading to BiocManager version 3.16 and R versions 4.2.1 and 4.2.2, but the problem persists.

Could you please help me troubleshoot this issue and suggest possible solutions? Thank you very much!

**Comment by Yun1229** [comment]
The problem has been solved.

**Comment by AndreaRMICL** [comment]
Hi @Yun1229 ! Sorry about my slow response. I missed your message; and I dd notice the same issue as you. The issue was due to some updates from the KEGG API side! Thanks
Andrea

**Comment by qqwxp** [comment]
> 

I am encountering the same error. How did you solve this?

**Comment by qqwxp** [comment]
I am encountering the same error. How did you solve this?

**Comment by AndreaRMICL** [comment]
Hi!

Should be solved in dev: https://www.bioconductor.org/packages/devel/bioc/html/MetaboSignal.html

But do let me know if it still doesn't work and I will look into it

Best, 

Andrea
